@startuml

Retrofit -> Api: create



activate Api

Api -> ServiceMethod:adapt

ServiceMethod -> Converter:convert

ServiceMethod <-- Converter

ServiceMethod -> CallAdapter:adapt

Api <-- CallAdapter:okHttpCall

Api -> CallAdapter

CallAdapter -> OkHttpCall:execute

activate OkHttpCall

OkHttpCall -> ServiceMethod:toCall

ServiceMethod -> okhttp3.Call: newCall

OkHttpCall ->> okhttp3.Call: execute

OkHttpCall <<-- okhttp3.Call:rawResponse

OkHttpCall -> ServiceMethod:toResponse

ServiceMethod -> Converter:convert

deactivate OkHttpCall

deactivate Api

@enduml